### PR TITLE
controlling and scheduling

### PR DESCRIPTION
**Pull request by TianYouX**
I have implement the "set schedule" and "cancel schedule" functions. When the set time arrives, it will automatically click the raise or lower button and cancel this schedule. Also, I added the text boxes and buttons listed in the "blind settings" section to this page.

### CODE REVIEW

**Review by adamb56789 — CHANGES_REQUESTED** [review]
1. Make sure you always link your pull requests to the Issue
1. This page is not for scheduling, it for settings of a single blind. Make sure you follow https://github.com/SDP-group22/Helio-app/issues/42. It will have a schedule button which opens something else, but do not worry about that for now - scheduling is in another ticket #44.
1. The editable text boxes do not work correctly. Instead of themselves containing text like "Name:" that should be placed adjacent to the box.
1. A few of the buttons on the list are missing
1. The icon selection should be a drop down menu
1. The Android SDK contains ways of making settings more easily. For example File->New-> Fragment->Settings Fragment. Try doing something like that. I think this is the guide for it [here](https://developer.android.com/guide/topics/ui/settings.html). The Save and Cancel buttons might not be necessary then. Try to fit the open and close buttons in separate from the settings, but if that is not possible just leave them out. Or maybe put them in the app bar. Or put them in the settings with everything else, though that will be a bit weird.
1. Try to use the `ConstraintLayout` instead of `RelativeLayout`. Though if you are using a `PreferenceScreen` this won't matter.

**Comment by TianYouX** [comment]
You changed the content of the issue #34. I thought we are going to combine scheduling and controlling into one page. Could you draw a simple graph for this page?

**Comment by adamb56789** [comment]
We settled on using a more complicated scheduling system that won't fit on the same page. The API specification gives you an idea of how it works. Scheduling has been moved to a separate issue. Issue #34 turned into the settings for a blind, though we might as well put controls on it as well. I recommend you use the [AndroidX Preference library](https://developer.android.com/guide/topics/ui/settings.html) for the different settings, though you could do something else if you wanted. It is up to you to design the page, as long as it has all of the features listed on #42, possibly excluding the save/cancel buttons if that can be implemented automatically.

**Review by adamb56789 — CHANGES_REQUESTED** [review]
### Progress on points from last review
1. N/A
2. This ticket is not for scheduling, so your code should not include that part. In addition, it does not follow the plan or the requirements of the API, so there is not much point in keeping it. As is explained in #42, the scheduling system will not work at all like this. Open the alarm app on your phone and see it works, it is supposed to be like that. The app is just for user input and to send data to the hub, the hub will do the work of following the schedule. Pressing UI buttons on a timer is an interesting way of doing things, but seems like a bad practice, and does not fit with the rest of the system.
3. The way you have implemented the text is a bit weird, and there is probably a better way of doing it, but it works. However, it would be much better to use `EditTextPreference` from the AndroidX preference library.
4. From #42, numbers 11 and 12 are not done
5. This is done, though not to a sufficient level. There are already ways to make menus with lists built in, but you have not used them making it somewhat confusing and also lower quality. The repetition of icon1, icon2, ect everywhere is very bad practice. There is almost certainly a better way of doing this in the Preference library (list of everything in it) or elsewhere.
6. The Preference library has not been used. I insist that you do use it. It will be much easier, will look better, and be easier for the users to understand and use. I will immediately reject any submissions which do not use it, unless an alternative is presented of equivalent quality, with an associated explanation.
7. Will not apply if using `Preference`
### Other comments
Please read or watch tutorials such as (this)[https://www.youtube.com/watch?v=fis26HvvDII], to make sure you know what is possible in Android and to stop your code from being rejected. If any of my English is too difficult to understand or you want clarification on something, just send me a message on teams.

**Review by adamb56789 — CHANGES_REQUESTED** [review]
This is good progress, let's try to flesh it out more.
- Use `app:useSimpleSummaryProvider="true"` on the text fragments so their value can be seen
- The categories don't have a clear purpose, remove them for now
- Try to make the text more descriptive so it is clear what the options do
- I think it would be good if we could have orange control buttons as well the preferences. Try putting the preferences fragment inside another fragment with the buttons, I think it might be possible. You could put some of the other buttons there too if you want, or just remove them for now.
- The icon selection still needs work. Try using something like a `Spinner` or something else like that. The current setup will not work. Also try to display the selected icon next to the icon text
- The IP number input was working a bit strangely, test it out to make sure that it is possible to enter IP addresses
- Do whatever you think looks good to you, I'm a terrible artist

**Review by adamb56789 — APPROVED** [review]
Looks ok.

**Pull request merged**
