### PR TITLE
Voice integration in hub fragment

### PR DESCRIPTION
**Pull request by TianYouX**
Before using the voice recognizer, open the microphone permission for android studio and Helio-app. Also, click the three dots at the bottom of the vertical bar beside emulator. Click 'Microphone' and then open 'Virtual microphone uses host audio input'.

### CODE REVIEW

**Comment by TianYouX** [comment]
I create four microphone buttons in the hub fragment since there are four different edit text boxes. For IP address, the length of number between dots varies. I can't think of another way to make it work. I know it looks weird.

**Review by adamb56789 — CHANGES_REQUESTED** [review]
We want the user to be able to control the blinds by speaking, possibly after pressing a single microphone button. I think it will be too hard to set up voice integration for the settings, there are other solutions built into android for people who really need that. Instead, put a button with a microphone symbol in the app bar (https://material.io/components/app-bars-top) or in a floating action button (https://material.io/components/buttons-floating-action-button) or something like that in the control page. The user should be able to control blinds by saying, for example:
-"open kitchen"
-"open blinds in kitchen"
-"open blinds in the kitchen"
-"open the blinds in the kitchen"
-"close the blinds in my bedroom"
-"blinds in hall to level 50"
Assuming that the blinds are named in the settings "kitchen", "bedroom", etc. One way of doing this is taking user input, searching for words that match the name of a blind, and search for words like "open", "close", "shut", "up", "down", and numbers like "50" for the target level. I'm not sure if this is a good approach, but it is an initial idea, and we probably want it keep things simple.

If it was easy to, could you also make it speak back to confirm what is happening, like "moving blinds in kitchen to closed"

**Comment by TianYouX** [comment]
I thought we are just going to add a speech-to-text function. I get what you mean. I can add a microphone symbol button in the control fragment and then be able to distinguish between open and close commands. But I have no idea how to search for existing blind names and then open or close specific blinds. This is hard.

**Comment by adamb56789** [comment]
Do this in the viewmodel. Get all the motors with `motors.getValues()`, and get there names with `.getName()`. Search through the names to see which of them is contained by the text from the text to speech. Then look for synonyms of "open" and "closed", as well as numbers.

**Comment by TianYouX** [comment]
Do you mean do this in "ControlRecViewAdapter" or "UserDataViewModel"?

**Comment by adamb56789** [comment]
I mean `UserDataViewModel`. The other one is for UI code, the code for interpreting the text should be in the model. Instead of adding a button in the control bar, add a button to the top app bar. See the other fragments to see how to get copies of the model.

**Comment by TianYouX** [comment]
Map userData = model.fetchMotors().getValue(); Is this right? Is the userData a Map<Integer,Motor>?

**Pull request closed without merging**
