### PR TITLE
All blinds control

### LINKED ISSUE #33: Develop page for direct manual control of blinds separately or together.
A page with sliders for multiple blinds.

Possibly also the main page.

### PR DESCRIPTION
**Pull request by adamb56789**
Added sliders for each motor on the control page that can be used to control the blinds. Also tried make instrumented tests but I can't get them to run for an unknown reason. It works when I make a new project with a template.
Issues can be added later for something to potentially be able to control everything at once etc.

Closes #33

### CODE REVIEW

**Review by nout-kleef — APPROVED** [review]
Looks good to me, but why do you use Kotlin for one of the files?

**Comment by adamb56789** [comment]
Because that's what the stackoverflow answer used. I wanted to get some tests up quickly so it could be mentioned in the demo, we can more on tests later. Could you run the tests? I couldn't get it to work at all. It either said "No tests found" or "Test framework quit unexpectedly".

**Comment by nout-kleef** [comment]
I'm running into this issue: https://discuss.kotlinlang.org/t/have-a-error-junit-version-3-8-or-later-expected/2558/5

Trying to work through it now.

**Comment by nout-kleef** [comment]
I can't figure it out either

**Pull request merged**
