### PR TITLE
Reduce warnings

### PR DESCRIPTION
**Pull request by TianYouX**

### CODE REVIEW

**Review by adamb56789 — CHANGES_REQUESTED** [review]
There are still a lot of warnings. You can run the inspection with Analyse -> Inspect code.
image

**Comment by TianYouX** [comment]
image
image
For this one, the whole class is unused. For the getView() warnings, I have no idea how to fix it.

**Comment by adamb56789** [comment]
The unused class can be deleted.
For the `getView()`, there is a solution suggested by Android Studio: 
image.

Doing this causes another warning, which can also be fixed:
image

Replacing `getView()` with `requireView()` should solve the warning.

**Comment by TianYouX** [comment]
image
This should be ok now.

**Review by adamb56789 — APPROVED** [review]
The only remaining warnings are unused resources for things that we want to keep, and typos that aren't actually typos, so I think that we can say that we have 0 warnings and errors.

**Pull request merged**
